FROM node:20

WORKDIR /app

RUN mkdir -p /app/auth_info_baileys && chown -R node:node /app

USER node

COPY --chown=node:node agent-pipeline/whatsapp-bridge-js/package*.json ./

RUN npm install

COPY --chown=node:node agent-pipeline/whatsapp-bridge-js .

CMD ["npm", "start"]