FROM node:20

WORKDIR /app

RUN chown node:node /app

USER node

COPY --chown=node:node agent-pipeline/frontend/package*.json ./

RUN npm install

COPY --chown=node:node agent-pipeline/frontend .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]