"""
Node: write
Uses Gemini (cloud) or local Gemma3 via Ollama to generate the newsletter.
"""
import os
from state import emit, pipeline_states

SYSTEM_PROMPT = """You are an expert tech newsletter writer for "AI Pulse Weekly".
Synthesise the research into an engaging markdown newsletter.

Format:
# 🚀 AI Pulse Weekly — {TOPIC} Digest

## This Week's Top Picks
(3-4 curated items with key insights, one per source)

## 💡 Key Takeaway
(one paragraph synthesis)

## 🔗 Resources
(list of source URLs)

---
*Generated by AI Pulse Agent Pipeline*

Keep it concise, punchy, and developer-friendly. Max 500 words."""


def write_node(state: dict) -> dict:
    run_id       = state["run_id"]
    topic        = state["topic"]
    model        = state.get("model", "gemini")
    research     = state.get("research_data", [])
    user_feedback = state.get("user_feedback")

    if user_feedback:
        emit(run_id, {
            "type": "step", "step": "write", "status": "in_progress",
            "message": f"✍️ Writer Agent — revising newsletter based on feedback...",
        })
        user_prompt = (
            f"You are revising the draft of 'AI Pulse Weekly' for {topic}.\n\n"
            f"Previous Draft:\n{state.get('newsletter', '')}\n\n"
            f"User Feedback for Revision: {user_feedback}\n\n"
            f"Write the revised newsletter now, incorporating all feedback and preserving correct markdown layout."
        )
    else:
        emit(run_id, {
            "type": "step", "step": "write", "status": "in_progress",
            "message": f"✍️ Writer Agent — generating newsletter with {model}...",
        })
        summaries = "\n\n".join(
            f"Source [{r.get('type','web').upper()}]: {r.get('title', r.get('url',''))}\n{r.get('summary','')[:1500]}"
            for r in research
        )
        user_prompt = f"Topic: {topic}\n\nResearch:\n{summaries}\n\nWrite the newsletter now."

    newsletter = _call_llm(model, topic, user_prompt)

    # Store in shared state for approval endpoint
    s = pipeline_states[run_id]
    s["newsletter"] = newsletter
    s["awaiting_approval"] = True
    s["approval"] = None
    s["user_feedback"] = None

    emit(run_id, {"type": "step", "step": "write", "status": "done"})
    emit(run_id, {"type": "newsletter_ready", "content": newsletter})

    return {**state, "newsletter": newsletter, "user_feedback": None}


def _call_llm(model: str, topic: str, user_prompt: str) -> str:
    selected = (os.environ.get("MODEL") or model or "gemini").lower()
    system   = SYSTEM_PROMPT.replace("{TOPIC}", topic)

    if selected in ("ollama", "gemma3", "local"):
        return _ollama(system, user_prompt)
    return _gemini(system, user_prompt)


def _gemini(system: str, user_prompt: str) -> str:
    import google.generativeai as genai
    api_key = os.environ.get("GEMINI_API_KEY") or os.environ.get("GOOGLE_API_KEY")
    if not api_key:
        raise ValueError("GEMINI_API_KEY not set")
    genai.configure(api_key=api_key)
    model = genai.GenerativeModel(
        model_name="gemini-2.5-flash",
        system_instruction=system,
    )
    response = model.generate_content(user_prompt)
    return response.text


def _ollama(system: str, user_prompt: str) -> str:
    from langchain_ollama import ChatOllama
    from langchain_core.messages import SystemMessage, HumanMessage
    llm = ChatOllama(model="gemma", base_url="http://localhost:11434", temperature=0.7)
    resp = llm.invoke([SystemMessage(content=system), HumanMessage(content=user_prompt)])
    return resp.content
